[pytest]
# Standardmäßig im Headed-Modus (Sichtbar) oder Headless (Hintergrund) ausführen
addopts = --base-url https://meine-minigolf-app.calmmoss-80fcb171.germanywestcentral.azurecontainerapps.io/ --browser chromium
#addopts = --browser chromium
